version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
  codecov: codecov/codecov@1.2.3
  heroku: circleci/heroku@1.2.6
jobs:
  ci_cd:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run tests with Jest
          command: npm run test:cov
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
      - sonarcloud/scan
      - codecov/upload:
          file: coverage/coverage-final.json
      - heroku/deploy-via-git
          #pre-steps:
          #  - run: npm install
          #post-steps:
          #  - run: your-database-migration-command

workflows:
  payments-workflow:
    jobs:
      - ci_cd:
          context: sonarcloud
